development:
  sessions:
    default:
      database: swayly_landing_development
      hosts:
        - linus.mongohq.com:10016
      username: swayly
      password: homey6(eunuchs

production:
  sessions:
    default:
      database: swayly_landing_production
      hosts:
        - linus.mongohq.com:10017
      username: swayly
      password: homey6(eunuchs
