development:
  sessions:
    default:
      database: swayly_landing_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: swayly_landing_production
      hosts:
        - linus.mongohq.com:10017
      username: swayly
      password: homey6(eunuchs
