development:
  sessions:
    default:
      database: swayly_landing_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: swayly_landing_production
      hosts:
        - dharma.mongohq.com:10064
      username: trunkit
      password: homey6(eunuchs
